import { CampusModuleInfo } from '@smart-campus/shared-types';

export const campusModules: CampusModuleInfo[] = [
  {
    id: 'auth-users',
    name: 'Identidade e Utilizadores (Core)',
    description: 'Gestao de autenticacao JWT, controlo de acesso RBAC e perfis de utilizadores.',
    status: 'available',
    category: 'core',
    route: '/api/v1/auth',
    requiredRoles: ['ADMIN', 'COORDINATOR'],
    teamMembers: ['Smart Campus Core Team'],
  },
  {
    id: 'buildings-campus',
    name: 'Edificios e Campus (Core)',
    description: 'Catalogo de edificios, blocos e infraestruturas do campus universitario.',
    status: 'available',
    category: 'infrastructure',
    route: '/api/v1/buildings',
    teamMembers: ['Smart Campus Core Team'],
  },
  {
    id: 'rooms-buildings',
    name: 'Salas e Espacos (Core)',
    description: 'Catalogo de espacos fisicos, laboratorios, salas de aula e auditorios.',
    status: 'available',
    category: 'infrastructure',
    route: '/api/v1/rooms',
    teamMembers: ['Smart Campus Core Team'],
  },
  {
    id: 'financial-students',
    name: 'Gestao Financeira de Estudantes',
    description: 'Modulo de dividas, pagamentos, estado financeiro, contestacoes, notificacoes, politicas e relatorios.',
    status: 'available',
    category: 'particular',
    route: '/api/v1/financial',
    requiredRoles: ['STUDENT', 'FINANCE', 'ADMIN'],
    teamMembers: ['Alipio Paco (2024080003)', 'Jesefa Mutemba'],
  },
  {
    id: 'audit-events',
    name: 'Auditoria e Rastreio',
    description: 'Consulta de eventos de auditoria e rastreamento de operacoes por correlationId.',
    status: 'available',
    category: 'core',
    route: '/api/v1/audit-events',
    requiredRoles: ['ADMIN', 'COORDINATOR'],
    teamMembers: ['Smart Campus Core Team'],
  },
  {
    id: 'dashboard-overview',
    name: 'Dashboard Operacional',
    description: 'Resumo estatistico do campus, ocupacao de salas e ocorrencias recentes.',
    status: 'available',
    category: 'core',
    route: '/api/v1/dashboard',
    teamMembers: ['Smart Campus Core Team'],
  },
];
